//created on: Apr 10, 2018
package rules

//list any import classes here.
import models.DiseaseTreatments;
import static services.HelperfunctionForTreatment.addTreatmentForDisease;


//declare any global variables here




rule "T01"

    when
        input: DiseaseTreatments(disease == "Dehydration")
    then
        addTreatmentForDisease("Dehydration","Go get help");

end

rule "T02"
    //include attributes such as "salience" here...
    when
         input: DiseaseTreatments(disease == "Dehydration")
    then
        addTreatmentForDisease("Dehydration","Go get help2");
end

rule "T03"
    //include attributes such as "salience" here...
    when
         input: DiseaseTreatments(disease == "chicken pox")
    then
        addTreatmentForDisease("chicken pox","Go get help3");

end


rule "T04"
    //include attributes such as "salience" here...
    when
         input: DiseaseTreatments(disease == "measles")
    then
        addTreatmentForDisease("measles","Go get help4");

end


